### ISSUE TITLE
Problem with downloading data from Reddit

### ISSUE THREAD

**Issue by christina284** [mediatechnologycenter/aestheval#13]
Hi, i created a reddit app, I used the APP ID as the CLIENT_ID env variable, the secret as the CLIENT_SECRET and my reddit username as the USER_AGENT. However I am not able to download the data. It seems like starting to downloading but it keeps warning about "items not found in Pushshift". How can I resolve this? I am attaching the exact error. 
![image](https://user-images.githubusercontent.com/30560364/221157960-513bc042-a981-412a-8893-d90a16155aec.png)

**Comment by dveni** [comment]
Hi! This is a known issue with Pushshift (see https://github.com/mediatechnologycenter/aestheval/issues/11#issuecomment-1427930918). Looks like it's still not working, feel free to reach out by email to give you access in the meantime.

I close this issue, please follow future updates in the other one.
