### ISSUE TITLE
Could you please share the dataset by gdirve link

### ISSUE THREAD

**Issue by evenhax** [mediatechnologycenter/aestheval#27]
Hi, would you please give me a Gdrive link ? I met errors when download with scrips, many thanks. (my mail is 1316396445@qq.com)

**Comment by evenhax** [comment]
Have been solved, thanks a lot.

**Comment by USTBhyh** [comment]
> Have been solved, thanks a lot.

How did you solve this problem? Can you share the method? Appreciate

**Comment by hopeSerendipity** [comment]
> Have been solved, thanks a lot.

Could you share the link with me?My email address is 2873068023@qq.com
